### ISSUE TITLE
Flyway 추가

### ISSUE THREAD

**Issue by daadaadaah** [f-lab-edu/hee-commerce#3]
## Why
- Flyway는 DB migrations 툴로, 서로 작업하면서 달라지는 DB 스키마에 대해 sync를 간편하게 맞추고 싶어서

> JPA 기능(`spring.jpa.hibernate.ddl-auto`)으로도 스키마 (엔티티)의 변경사항을 관리할 수 있지 않나?
> - 물론 가능하다. 그런데, 이게 운영환경이라면 조금 위험한 부분이 있다. 예를 들어, 실수로 ddl-auto의 설정값을 변경하면 데이터가 모조리 지워지는 끔직한 상황이 생길 수 있다. 그런데, flyway를 사용하면, git처럼 DB 관련에 대해 버전 관리가 되어, 실수로 데이터를 지웠을 때, 개발자가 원하는 시점의 스키마 상태로 되돌아갈 수 있다.

## How
- (보류)

## Comment
- 일단 빠르게 기능 구현하는 것을 목표로 하고 있고, 현재 운영단계도 아니니, 일단 flyway 사용을 보류하기로 함. 일단 JPA 기능으로 스키마 (엔티티)의 변경사항을 자동으로 DB에 적용하기로 결정함.

## Reference
- https://documentation.red-gate.com/fd/migrations-184127470.html

**Comment by f-lab-TJ** [comment]
왜 Flyway가 필요한지, 사용하려고하는지 잘 이해가 안되는데, 추가 설명 해 주실 수 있을까요?

**Comment by daadaadaah** [comment]
> 왜 Flyway가 필요한지, 사용하려고하는지 잘 이해가 안되는데, 추가 설명 해 주실 수 있을까요?

@f-lab-TJ  
1. 예를 들어, 저의 local DB에는 order 라는 테이블에는 컬럼 id, name, price 에 있었는데, 태희님이 order 기능을 작업을 해보면 몇가지 추가할 컬럼이나 수정 사항이 생길 경우, 저의 Local DB 스키마를 태희님이 새로 만든 order 스키마로 변경을 변경해줘야 하고, 이런 변경에 따라 테스트 데이터 수정도 필요합니다. 이렇게 변경된 스키마나 데이터 추가 작업을 코드화 시켜 "자동으로" 해주는 DB migration 툴이 있으면 좋겠다는 생각을 했습니다. 만약, flyway를 사용하지 않는다면, 제가 "수동으로" 저의 local DB에 스키마 변경 SQL를 계속 날려야 하고, 추가로 테스트 데이터도 제가 일일히 넣어줘야 하는 불편함이 있을 것 같았습니다. 
2. 저희가 배포해놓은 DB와 앞으로 배포할 DB 스키마가 다를 때, flyway를 사용할 경우 애플리케이션을 자동으로 실행시키면 자동으로 변경된 DB 스키마로 바꿔주는 장점이 있습니다.
